name: ci

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    env:
      NODE_NO_WARNINGS: 1
      BROWSERSLIST_IGNORE_OLD_DATA: 1
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Pnpm Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
